// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MossApp.Data;

namespace MossApp.Data.Migrations
{
    [DbContext(typeof(MossResultsContext))]
    [Migration("20211024220811_Intitial")]
    partial class Intitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MossApp.Data.Models.MatchPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlphaFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AlphaLines")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("AlphaPassage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("AlphaScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BetaFileName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BetaLines")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("BetaPassage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BetaScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LinesMatched")
                        .HasColumnType("int");

                    b.Property<int>("ResultsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResultsId");

                    b.HasIndex(new[] { "Id" }, "IX_MatchPairs_ResultId");

                    b.ToTable("MatchPairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlphaFileName = "AlphaFile",
                            AlphaScore = 66.6m,
                            BetaFileName = "BetaFile",
                            BetaLines = "43 - 51",
                            BetaScore = 33.3m,
                            LinesMatched = 45,
                            ResultsId = 1
                        });
                });

            modelBuilder.Entity("MossApp.Data.Models.Results", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Options")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Results");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateSubmitted = new DateTime(2021, 10, 24, 17, 8, 10, 670, DateTimeKind.Local).AddTicks(1193),
                            Options = "example options"
                        });
                });

            modelBuilder.Entity("MossApp.Data.Models.MatchPair", b =>
                {
                    b.HasOne("MossApp.Data.Models.Results", "Results")
                        .WithMany("MatchPairs")
                        .HasForeignKey("ResultsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Results");
                });

            modelBuilder.Entity("MossApp.Data.Models.Results", b =>
                {
                    b.Navigation("MatchPairs");
                });
#pragma warning restore 612, 618
        }
    }
}
